CREATE TABLE Donatii (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nume NVARCHAR(100) NOT NULL,
    Prenume NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    Suma DECIMAL(10,2) NOT NULL,
    DataDonatiei DATETIME NOT NULL
);
