-- Verifică collation la nivel de tabel
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, COLLATION_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Animale'

-- Setează collation la nivel de coloană
ALTER TABLE Animale ALTER COLUMN Nume NVARCHAR(255) COLLATE Latin1_General_CI_AI;
ALTER TABLE Animale ALTER COLUMN Specie NVARCHAR(255) COLLATE Latin1_General_CI_AI;
ALTER TABLE Animale ALTER COLUMN Varsta NVARCHAR(255) COLLATE Latin1_General_CI_AI;
ALTER TABLE Animale ALTER COLUMN Descriere NVARCHAR(MAX) COLLATE Latin1_General_CI_AI;
